CREATE PROC XEM_NHAN_VIEN
AS
BEGIN
SELECT * FROM NHANVIEN
END

CREATE PROC THEM_NHAN_VIEN(
@TEN_NV NVARCHAR(50),
@GIOI_TINH BIT,
@SDT NCHAR(10),
@DIA_CHI NVARCHAR(50),
@MK INT
)
AS
BEGIN
INSERT INTO NHANVIEN(TENNV,GIOITINH,SDT,DIACHI,MK) VALUES(@TEN_NV,@GIOI_TINH,@SDT,@DIA_CHI,@MK)
END

CREATE PROC SUA_NHAN_VIEN(
@MA_NV INT,
@TEN_NV NVARCHAR(50),
@GIOI_TINH BIT,
@SDT NCHAR(10),
@DIA_CHI NVARCHAR(50),
@MK INT
)
AS
BEGIN
UPDATE NHANVIEN SET TENNV=@TEN_NV,GIOITINH=@GIOI_TINH,SDT=@SDT,DIACHI=@DIA_CHI,MK=@MK WHERE MANV=@MA_NV
END

CREATE PROC XOA_NHAN_VIEN(
@MA_NV INT
)
AS
BEGIN
DELETE FROM NHANVIEN WHERE MANV=@MA_NV
END
